SELECT * FROM shows WHERE title LIKE '%the office%' OR title LIKE '%office%' OR title LIKE '%Thevoffice%';
UPDATE shows SET title = 'The Office' WHERE title LIKE '%the office%' OR title LIKE '%office%' OR title LIKE '%Thevoffice%';
SELECT * FROM shows WHERE title LIKE '%arrow%';
UPDATE shows SET title = 'Arrow' WHERE title LIKE '%arrow%';
SELECT * FROM shows WHERE title LIKE '%adventure time%';
UPDATE shows SET title = 'Adventure Time' WHERE title LIKE '%adventure time%';
SELECT * FROM shows WHERE title LIKE '%avatar the last airbender%';
UPDATE shows SET title = 'Avatar: The Last Airbender' WHERE title LIKE '%avatar the last airbender%';
SELECT * FROM shows WHERE title LIKE '%brooklyn 99%' OR title LIKE '%b99%' OR title LIKE '%brooklyn-99%';
UPDATE shows SET title = 'Brooklyn Nine-Nine' WHERE title LIKE '%brooklyn 99%' OR title LIKE '%b99%' OR title LIKE '%brooklyn-99%';
SELECT * FROM shows WHERE title LIKE '%community%';
UPDATE shows SET title = 'Community' WHERE title LIKE '%community%';
SELECT * FROM shows WHERE title LIKE '%family guy%';
UPDATE shows SET title = 'Family Guy' WHERE title LIKE '%family guy%';
SELECt * FROM shows WHERE title LIKE '%friends%';
UPDATE shows SET title = 'Friends' WHERE title Like '%friends%';
SELECT * FROM shows WHERE title LIKE '%game of thrones%' OR title LIKE '%got%';
UPDATE shows SET title = 'Game of Thrones' WHERE title LIKE '%game of thrones%' OR title LIKE '%got%';
SELECT * FROM shows WHERE title LIKE '%gilmore girls%'
UPDATE shows SET title = 'Gilmore Girls' WHERE title LIKE '%gilmore girls%';
SELECT * FROM shows WHERE title LIKE '%Grey''s anatomy%';
UPDATE shows SET title = 'Grey''s Anatomy' WHERE title LIKE '%Grey''s anatomy%';
SELECT * FROM shows WHERE title LIKE '%its always sunny in philidelphia%';
UPDATE shows SET title = 'It''s Always Sunny in Philidelphia' WHERE title LIKE '%its always sunny in philidelphia%';
SELECT * FROM shows WHERE title LIKE '%parks and %';
UPDATE shows SET title = 'Parks and Recreation' WHERE title LIKE '%parks and %';
SELECT * FROM shows WHERE title LIKE '%sherlock%';
UPDATE shows SET title = 'Sherlock' WHERE title like '%sherlock%';
SELECT * FROM shows WHERE title LIKE '%squid%';
UPDATE shows SET title = 'Squid Game' WHERE title LIKE '%squid%';
SELECT * FROM shows WHERE title LIKE '%the bachelorette%';
UPDATE shows SET title = 'The Bachelorette' WHERE title LIKE '%the bachelorette%';
SELECT * FROM shows WHERE title LIKE '%the crown%';
UPDATE shows SET title = 'The Crown' WHERE title LIKE '%the crown%';
SELECT * FROM shows WHERE title LIKE '%Queen''s Gambit%';
UPDATE shows SET title ='The Queen''s Gambit'  WHERE title LIKE '%Queen''s Gambit%';
SELECT * FROM shows WHERE title LIKE '%law and order%';
UPDATE shows SEt title = 'Law and Order' WHERE title LIKE '%law and order%';
SELECT * FROM shows WHERE title LIKE '%criminal minds%';
UPDATE shows SET title = 'Criminal Minds' WHERE title LIKE '%criminal minds%';
SELECT * FROM shows WHERE title LIKE '%billions%';
UPDATE shows SET title = 'Billions' WHERE title LIKE '%billions%';
SELECT * FROM shows WHERE title LIKE '%the untamed%';
UPDATE shows SET title = 'The Untamed' WHERE title LIKE '%the untamed%';
